/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedStocktakeRouteImport } from './routes/_authenticated/stocktake'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedMembershipsRouteImport } from './routes/_authenticated/memberships'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInstallmentsRouteImport } from './routes/_authenticated/installments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractFarmingRouteImport } from './routes/_authenticated/contract-farming'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedBeneficiariesRouteImport } from './routes/_authenticated/beneficiaries'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedVouchersIndexRouteImport } from './routes/_authenticated/vouchers.index'
import { Route as AuthenticatedVouchersReceiptsRouteImport } from './routes/_authenticated/vouchers.receipts'
import { Route as AuthenticatedVouchersPaymentsRouteImport } from './routes/_authenticated/vouchers.payments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStocktakeRoute = AuthenticatedStocktakeRouteImport.update({
  id: '/stocktake',
  path: '/stocktake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembershipsRoute =
  AuthenticatedMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstallmentsRoute =
  AuthenticatedInstallmentsRouteImport.update({
    id: '/installments',
    path: '/installments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractFarmingRoute =
  AuthenticatedContractFarmingRouteImport.update({
    id: '/contract-farming',
    path: '/contract-farming',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBeneficiariesRoute =
  AuthenticatedBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVouchersIndexRoute =
  AuthenticatedVouchersIndexRouteImport.update({
    id: '/vouchers/',
    path: '/vouchers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVouchersReceiptsRoute =
  AuthenticatedVouchersReceiptsRouteImport.update({
    id: '/vouchers/receipts',
    path: '/vouchers/receipts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVouchersPaymentsRoute =
  AuthenticatedVouchersPaymentsRouteImport.update({
    id: '/vouchers/payments',
    path: '/vouchers/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/beneficiaries': typeof AuthenticatedBeneficiariesRoute
  '/cash': typeof AuthenticatedCashRoute
  '/contract-farming': typeof AuthenticatedContractFarmingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/items': typeof AuthenticatedItemsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stocktake': typeof AuthenticatedStocktakeRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/vouchers/payments': typeof AuthenticatedVouchersPaymentsRoute
  '/vouchers/receipts': typeof AuthenticatedVouchersReceiptsRoute
  '/vouchers/': typeof AuthenticatedVouchersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/beneficiaries': typeof AuthenticatedBeneficiariesRoute
  '/cash': typeof AuthenticatedCashRoute
  '/contract-farming': typeof AuthenticatedContractFarmingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/items': typeof AuthenticatedItemsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stocktake': typeof AuthenticatedStocktakeRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/': typeof AuthenticatedIndexRoute
  '/vouchers/payments': typeof AuthenticatedVouchersPaymentsRoute
  '/vouchers/receipts': typeof AuthenticatedVouchersReceiptsRoute
  '/vouchers': typeof AuthenticatedVouchersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/beneficiaries': typeof AuthenticatedBeneficiariesRoute
  '/_authenticated/cash': typeof AuthenticatedCashRoute
  '/_authenticated/contract-farming': typeof AuthenticatedContractFarmingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/installments': typeof AuthenticatedInstallmentsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/memberships': typeof AuthenticatedMembershipsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/stocktake': typeof AuthenticatedStocktakeRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vouchers/payments': typeof AuthenticatedVouchersPaymentsRoute
  '/_authenticated/vouchers/receipts': typeof AuthenticatedVouchersReceiptsRoute
  '/_authenticated/vouchers/': typeof AuthenticatedVouchersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/beneficiaries'
    | '/cash'
    | '/contract-farming'
    | '/dashboard'
    | '/installments'
    | '/invoices'
    | '/items'
    | '/journal'
    | '/loans'
    | '/memberships'
    | '/projects'
    | '/stock'
    | '/stocktake'
    | '/units'
    | '/vouchers/payments'
    | '/vouchers/receipts'
    | '/vouchers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/beneficiaries'
    | '/cash'
    | '/contract-farming'
    | '/dashboard'
    | '/installments'
    | '/invoices'
    | '/items'
    | '/journal'
    | '/loans'
    | '/memberships'
    | '/projects'
    | '/stock'
    | '/stocktake'
    | '/units'
    | '/'
    | '/vouchers/payments'
    | '/vouchers/receipts'
    | '/vouchers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/accounts'
    | '/_authenticated/beneficiaries'
    | '/_authenticated/cash'
    | '/_authenticated/contract-farming'
    | '/_authenticated/dashboard'
    | '/_authenticated/installments'
    | '/_authenticated/invoices'
    | '/_authenticated/items'
    | '/_authenticated/journal'
    | '/_authenticated/loans'
    | '/_authenticated/memberships'
    | '/_authenticated/projects'
    | '/_authenticated/stock'
    | '/_authenticated/stocktake'
    | '/_authenticated/units'
    | '/_authenticated/'
    | '/_authenticated/vouchers/payments'
    | '/_authenticated/vouchers/receipts'
    | '/_authenticated/vouchers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stocktake': {
      id: '/_authenticated/stocktake'
      path: '/stocktake'
      fullPath: '/stocktake'
      preLoaderRoute: typeof AuthenticatedStocktakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memberships': {
      id: '/_authenticated/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedMembershipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/installments': {
      id: '/_authenticated/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof AuthenticatedInstallmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contract-farming': {
      id: '/_authenticated/contract-farming'
      path: '/contract-farming'
      fullPath: '/contract-farming'
      preLoaderRoute: typeof AuthenticatedContractFarmingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/beneficiaries': {
      id: '/_authenticated/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AuthenticatedBeneficiariesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vouchers/': {
      id: '/_authenticated/vouchers/'
      path: '/vouchers'
      fullPath: '/vouchers/'
      preLoaderRoute: typeof AuthenticatedVouchersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vouchers/receipts': {
      id: '/_authenticated/vouchers/receipts'
      path: '/vouchers/receipts'
      fullPath: '/vouchers/receipts'
      preLoaderRoute: typeof AuthenticatedVouchersReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vouchers/payments': {
      id: '/_authenticated/vouchers/payments'
      path: '/vouchers/payments'
      fullPath: '/vouchers/payments'
      preLoaderRoute: typeof AuthenticatedVouchersPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedBeneficiariesRoute: typeof AuthenticatedBeneficiariesRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRoute
  AuthenticatedContractFarmingRoute: typeof AuthenticatedContractFarmingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstallmentsRoute: typeof AuthenticatedInstallmentsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedMembershipsRoute: typeof AuthenticatedMembershipsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedStocktakeRoute: typeof AuthenticatedStocktakeRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVouchersPaymentsRoute: typeof AuthenticatedVouchersPaymentsRoute
  AuthenticatedVouchersReceiptsRoute: typeof AuthenticatedVouchersReceiptsRoute
  AuthenticatedVouchersIndexRoute: typeof AuthenticatedVouchersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedBeneficiariesRoute: AuthenticatedBeneficiariesRoute,
  AuthenticatedCashRoute: AuthenticatedCashRoute,
  AuthenticatedContractFarmingRoute: AuthenticatedContractFarmingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstallmentsRoute: AuthenticatedInstallmentsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedMembershipsRoute: AuthenticatedMembershipsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedStocktakeRoute: AuthenticatedStocktakeRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVouchersPaymentsRoute: AuthenticatedVouchersPaymentsRoute,
  AuthenticatedVouchersReceiptsRoute: AuthenticatedVouchersReceiptsRoute,
  AuthenticatedVouchersIndexRoute: AuthenticatedVouchersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
